### ISSUE TITLE
tag naming

### ISSUE THREAD

**Issue by IzzySoft** [hardalgorithm/ParanoidsPal-PrivacyLock#1]
Could you please give your tags/releases dedicated names? "lastest" is a "moving target". That makes e.g. [Reproducible Builds](https://reproducible-builds.org/) impossible, as they'd fail to verify as soon as you tag again. Your current release tag should better be named `v1.1.3`, matching `versionName` (though that has an unneeded dot after the `v`) and what you wrote in its notes.

And while I'm here:

```
! repo/com.paranoid.privacylock_5.apk declares sensitive permission(s): android.permission.REQUEST_DELETE_PACKAGES
! repo/com.paranoid.privacylock_5.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Can you pleaseexplain what `REQUEST_DELETE_PACKAGES` is needed for? I find no reference in the description. As for `DEPENDENCY_INFO_BLOCK`, that's easily avoided with a minor addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Thanks in advance!

**Comment by IzzySoft** [comment]
PS: if you'd use asterisks (`*`) as bullet points [here](https://github.com/hardalgorithm/ParanoidsPal-PrivacyLock/blob/master/metadata/en-US/full_description.txt#L5) and remove the empty line between the two, your full description would render fine as Markdown :wink:

That said, your app will [become available here](https://apt.izzysoft.de/packages/com.paranoid.privacylock) with the next sync around 6 pm UTC (i.e. in about 3h from now), albeit without RB (see above: tag names). Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) and link there e.g. from your Readme :smiley:

PS: in case someone asks, [VT](https://www.virustotal.com/gui/file/d2c9630f60087db2147a1616f3c55d62d88b63c9eb19c112953a38c654d36654/detection/f-d2c9630f60087db2147a1616f3c55d62d88b63c9eb19c112953a38c654d36654-1729766744) says Trustlook doesn't like the current release (obviously a "false positive", as 65 other engines disagree).

**Comment by hardalgorithm** [comment]
Thanks for the review 👍

✅ Renamed the release tags
✅ In full_desc removed blank line between and replaced with (*)
✅ Added a link to IzzyOnDroid in README.MD
✅ Upgraded my build.gradle for (DEPENDENCY_INFO_BLOCK; GOOGLE)

❔My app asks the user for Admin permissions (to lock the screen) but when the user wants to delete the app he has to look for where to take this permissions away from the app (many people find it difficult to look for the Admin permissions setting). I didn't like this situation as it would leave a bad impression and so I added a button “Uninstall app” in the application - where I select the permissions myself and remove my application from the system for this purpose I need 
REQUEST_DELETE_PACKAGES

**Comment by IzzySoft** [comment]
Thanks! Now, can you please provide an APK built from that commit (ce2cf695caf457a4d404b4ece179a8fe43d5610a)? The one attached to your release was built from a dirty tree at 74e677b936575a70080de78fc774042235c21bcb, with the dependencyInfo block removed, but you then adjusted `versionName` **after** the build and only then committed. Built from a clean tree, your app would be reproducible (see: [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)).

APK diff against the tagged commit (74e677b936575a70080de78fc774042235c21bcb):

```diff
  -rw----     2.0 fat     2426 b-     1286 defN 1981-01-01 01:01:02 7e3e3d18 kotlin/reflect/reflect.kotlin_builtins
- -rw----     0.0 fat    11064 b-     2736 defN 1981-01-01 01:01:02 db9e90d4 AndroidManifest.xml
+ -rw----     0.0 fat    11064 b-     2734 defN 1981-01-01 01:01:02 6c5af304 AndroidManifest.xml
  -rw----     0.0 fat      744 b-      342 defN 1981-01-01 01:01:02 9267afec res/-1.xml
```

Diff of that manifest:

```
       ATTR: http://schemas.android.com/apk/res/android:versionCode=5
-      ATTR: http://schemas.android.com/apk/res/android:versionName='v1.1.3'
+      ATTR: http://schemas.android.com/apk/res/android:versionName='v.1.1.3'
       ATTR: http://schemas.android.com/apk/res/android:compileSdkVersion=35
```

If I build from ce2cf695caf457a4d404b4ece179a8fe43d5610a:

```diff
  -rw-r--r--  0.0 unx       56 b-       51 defN 1981-01-01 01:01:02 193e2587 META-INF/com/android/build/gradle/app-metadata.properties
- -rw-r--r--  0.0 unx      120 b-      118 defN 1981-01-01 01:01:02 abf9437f META-INF/version-control-info.textproto
- -rw-r--r--  0.0 unx     2230 b-     2230 stor 1981-01-01 01:01:02 e76521df assets/dexopt/baseline.prof
+ -rw-r--r--  0.0 unx      120 b-      118 defN 1981-01-01 01:01:02 8a760138 META-INF/version-control-info.textproto
+ -rw-r--r--  0.0 unx     2231 b-     2231 stor 1981-01-01 01:01:02 c7680d2c assets/dexopt/baseline.prof
  -rw-r--r--  0.0 unx      316 b-      316 stor 1981-01-01 01:01:02 24bbb9e6 assets/dexopt/baseline.profm
- -rw-r--r--  0.0 unx  1909736 b-  1909736 stor 1981-01-01 01:01:02 510fc27b classes.dex
+ -rw-r--r--  0.0 unx  1909736 b-  1909736 stor 1981-01-01 01:01:02 f8b56c2b classes.dex
  -rw-r--r--  0.0 unx   245478 b-   243691 defN 1981-01-01 01:01:02 43c585e5 assets/lottielab-json-to-dotlottie.lottie
```

where `META-INF/version-control-info.textproto` of your APK tells me the other commit, and the Dex gives:

```diff
 |: iget-object v12, v12, Lh4/a;.l:Landroid/widget/TextView;
-|: const-string v0, "v.1.1.3"
+|: const-string v0, "v1.1.3"
 |: invoke-virtual {v12, v0}, Landroid/widget/TextView;.setText:(Ljava/lang/CharSequence;)V
 |: new-instance v12, Lp4/c;
 |: invoke-direct {v12}, Lp4/c;.<init>:()V
@@ -369422,7 +369422,7 @@
 |: const/4 v0, #int 2 // #2
 |: invoke-interface {v3, v0}, Landroid/view/Menu;.getItem:(I)Landroid/view/MenuItem;
 |: move-result-object v3
-|: const-string v0, "Version           v.1.1.3"
+|: const-string v0, "Version           v1.1.3"
 |: invoke-interface {v3, v0}, Landroid/view/MenuItem;.setTitle:(Ljava/lang/CharSequence;)Landroid/view/MenuItem;
```

So my build reflects the corrected `versionName`, which was not yet fixed in your APK, but the dependencyInfo blob was already gone in your APK. Hence my deduction of what must have happened at your side: remove blob => build => adjust versionName => commit :man_shrugging:

First basic rule from our [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds): Always build your APK from a clean tree at the commit the release tag points to :stuck_out_tongue_winking_eye: One more rule: never replace APKs that were already distributed. So if you stick to those two rules, I'm confident your next release will be reproducible. Please give me a ping when you have a new release ready (incl. increased `versionCode`, as that's what Android uses internally to tell releases apart).

Thanks for the explanation of the permission! Added that to the green list then:

![image](https://github.com/user-attachments/assets/a6095f02-2af0-4c7e-8ae4-7f12a09ab4f5)

App description will be updated from fastlane with the next release then automatically.

**Comment by hardalgorithm** [comment]
Thanks for the clarification, IzzySoft 🤝
I've created a new release (v1.1.4) with removed blod and latest commit [45e722c](https://github.com/hardalgorithm/ParanoidsPal-PrivacyLock/commit/45e722c26b47cf52a480ef83599e414057e603df)
I hope it's correct now 👾

**Comment by IzzySoft** [comment]
Confirmed: v1.1.4 has the blob removed. [Trustlook is complaining](https://www.virustotal.com/gui/file/58da6cec5c97f546076ad1e572dd06732204cb27568a760f461da9ce54a2e360/detection/f-58da6cec5c97f546076ad1e572dd06732204cb27568a760f461da9ce54a2e360-1729964303), but as the other 60+ engines show all lights green, we can consider that a "false positive".

Now let's see for RB… It's not:

```diff
 |: iget-object v12, v12, Lh4/a;.l:Landroid/widget/TextView;
-|: const-string v0, "v1.1.3"
+|: const-string v0, "v1.1.4"
 |: invoke-virtual {v12, v0}, Landroid/widget/TextView;.setText:(Ljava/lang/CharSequence;)V
 |: new-instance v12, Lp4/c;
 |: invoke-direct {v12}, Lp4/c;.<init>:()V
@@ -369422,7 +369422,7 @@
 |: const/4 v0, #int 2 // #2
 |: invoke-interface {v3, v0}, Landroid/view/Menu;.getItem:(I)Landroid/view/MenuItem;
 |: move-result-object v3
-|: const-string v0, "Version           v1.1.3"
+|: const-string v0, "Version           v1.1.4"
 |: invoke-interface {v3, v0}, Landroid/view/MenuItem;.setTitle:(Ljava/lang/CharSequence;)Landroid/view/MenuItem;
```

Which is strange, as both APKs identify with v1.1.4. But the DEX of your APK somewhere still has a `v1.1.3` inside – while the one I just built from the commit your tag points to has not. Vague guess: did you build yours shortly before committing 45e722c, and then did a last change before finally calling `git commit`? Hm, no, then versionInfo could not have that commit hash inside. Some cached artifacts maybe? How did you build? Some GUI, or command-line? We're sooo close there…

**Comment by hardalgorithm** [comment]
I build apk from android studio via generated signed apk. First commit then build apk.
Maybe the AS has cached something. 
Now I'll try clean project and invalidate caches.

**Comment by IzzySoft** [comment]
> Maybe the AS has cached something.

Yupp, it usually has. May I suggest inserting a step? Before you run "generate", please run "clean". If you can provide an APK built from the same commit that way (or from a later commit which you'd then need to mention to me) I can test that again. Ideally from the same commit, so we can compare and tell for sure if we found the culprit.

Thanks!

**Comment by hardalgorithm** [comment]
Check please [v1.1.4](https://github.com/hardalgorithm/ParanoidsPal-PrivacyLock/releases/tag/v1.1.4) with this [apk](https://github.com/hardalgorithm/ParanoidsPal-PrivacyLock/releases/download/v1.1.4/app-release-v114.apk)
I decompile apk and double-checked the version and it's the latest. 
Looks like the problem was building with an old android studio cache 😔
PS: now [VT](https://www.virustotal.com/gui/file/58da6cec5c97f546076ad1e572dd06732204cb27568a760f461da9ce54a2e360/detection/f-58da6cec5c97f546076ad1e572dd06732204cb27568a760f461da9ce54a2e360-1729964303) undetected virus, but it's old version 👀

**Comment by IzzySoft** [comment]
Thanks! And :partying_face: I can confirm it's RB! Unfortunately, **this release** won't show RB at IzzyOnDroid, as you replaced the APK at a tag/release that was already pulled (one should not replace what was already published). Would have been better had you created a "maintenance release" after my checking – but well, what's done is done (just please don't change it again, now that the RB has been established, as that would break the RB status). The next release should then properly show the "green shield" :crossed_fingers:

> Looks like the problem was building with an old android studio cache

Yepp, it does that when not cleaned before – for faster builds. So does gradle by the way, if you don't tell it to clean first.

That said, [welcome to the RB family](https://floss.social/@IzzyOnDroid/113380085779842073) :smiley: 

![image](https://github.com/user-attachments/assets/857a636d-ee4c-4a12-ae91-8ed3b95587f4)

As everything discussed here should be addressed now, I'll close the issue. Should I have forgotten something, feel free to reopen of course!
